# Generated by Django 4.2.9 on 2024-04-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_alter_patient_examine_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientExamine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('femur_image', models.ImageField(upload_to='', verbose_name='femur_image')),
                ('head_image', models.ImageField(upload_to='', verbose_name='femur_image')),
                ('femur_pixel_depth', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='femur_pixel_depth')),
                ('head_pixel_depth', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='head_pixel_depth')),
                ('femur_number', models.IntegerField(blank=True, null=True, verbose_name='femur_number')),
                ('femur_length', models.IntegerField(blank=True, null=True, verbose_name='femur_length')),
                ('gestational_age', models.IntegerField(blank=True, null=True, verbose_name='gestational_age')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
    ]
