# Generated by Django 4.2.9 on 2024-04-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_examine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientexamine',
            name='femur_pixel_depth',
            field=models.DecimalField(decimal_places=20, max_digits=22, verbose_name='femur_pixel_depth'),
        ),
        migrations.AlterField(
            model_name='patientexamine',
            name='head_pixel_depth',
            field=models.DecimalField(decimal_places=20, max_digits=22, verbose_name='head_pixel_depth'),
        ),
    ]
