# Generated by Django 4.2.9 on 2024-04-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_examine', '0003_remove_patientexamine_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientexamine',
            name='femur_number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='femur_number'),
        ),
        migrations.AlterField(
            model_name='patientexamine',
            name='femur_pixel_depth',
            field=models.FloatField(verbose_name='femur_pixel_depth'),
        ),
        migrations.AlterField(
            model_name='patientexamine',
            name='head_pixel_depth',
            field=models.FloatField(verbose_name='head_pixel_depth'),
        ),
    ]
