# Generated by Django 4.2.9 on 2024-04-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_examine'),
        ('patient_examine', '0004_alter_patientexamine_femur_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientexamine',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='patients.patient'),
        ),
    ]
