# Generated by Django 4.2.9 on 2024-04-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patient_examine'),
        ('patient_examine', '0005_patientexamine_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientexamine',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='patients.patient'),
        ),
    ]
