# Generated by Django 4.2.9 on 2024-04-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_examine', '0006_alter_patientexamine_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientexamine',
            name='patient',
        ),
    ]
