# Generated by Django 4.2.9 on 2024-04-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_examine', '0007_remove_patientexamine_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFemurExamine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('femur_image', models.ImageField(upload_to='', verbose_name='femur_image')),
                ('pixel_depth', models.FloatField(verbose_name='pixel_depth')),
                ('femur_length', models.IntegerField(blank=True, null=True, verbose_name='femur_length')),
                ('femur_age', models.IntegerField(blank=True, null=True, verbose_name='femur_age')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHeadExamine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('head_image', models.ImageField(upload_to='', verbose_name='head_image')),
                ('pixel_depth', models.FloatField(verbose_name='pixel_depth')),
                ('circumference', models.IntegerField(blank=True, null=True, verbose_name='femur_age')),
                ('gestational_age', models.IntegerField(blank=True, null=True, verbose_name='femur_age')),
            ],
        ),
    ]
