# Generated by Django 4.2.9 on 2024-04-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_examine', '0008_patientfemurexamine_patientheadexamine'),
        ('patients', '0009_remove_patient_examine_patient_femur_examine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientExamine',
        ),
    ]
