# Generated by Django 4.2.9 on 2024-04-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_examine', '0009_delete_patientexamine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientheadexamine',
            old_name='circumference',
            new_name='head_circumference',
        ),
    ]
