# Generated by Django 4.2.9 on 2024-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('first_name', models.CharField(max_length=255, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=255, verbose_name='first_name')),
                ('date_of_birth', models.DateField(max_length=8, verbose_name='date_of_birth')),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=1, verbose_name='gender')),
                ('examine_date', models.DateField(max_length=8, verbose_name='examine_date')),
                ('trimester', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], max_length=1, verbose_name='trimester')),
                ('blood_group', models.CharField(max_length=2, verbose_name='blood_group')),
                ('age', models.IntegerField(verbose_name='age')),
                ('examine_by', models.CharField(max_length=255, verbose_name='examine_by')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile_image')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
        ),
    ]
