# Generated by Django 4.2.9 on 2024-03-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last_name'),
        ),
    ]
