# Generated by Django 4.2.9 on 2024-04-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0004_remove_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='examine_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
    ]
