# Generated by Django 4.2.9 on 2024-04-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_examine', '0003_remove_patientexamine_patient'),
        ('patients', '0005_alter_patient_examine_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='examine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_examine.patientexamine'),
        ),
    ]
