# Generated by Django 4.2.9 on 2024-04-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_examine', '0005_patientexamine_patient'),
        ('patients', '0007_alter_patient_examine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='examine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examine', to='patient_examine.patientexamine'),
        ),
    ]
