# Generated by Django 4.2.9 on 2024-04-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_examine', '0008_patientfemurexamine_patientheadexamine'),
        ('patients', '0008_alter_patient_examine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='examine',
        ),
        migrations.AddField(
            model_name='patient',
            name='femur_examine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='femur_examine', to='patient_examine.patientfemurexamine'),
        ),
        migrations.AddField(
            model_name='patient',
            name='head_examine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_examine', to='patient_examine.patientheadexamine'),
        ),
    ]
