# Generated by Django 4.2.9 on 2024-04-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='gender')),
                ('qualification', models.CharField(max_length=255, verbose_name='qualification')),
                ('specialization', models.CharField(max_length=255, verbose_name='specialization')),
            ],
        ),
    ]
